/**
 * emit-ts.test.ts — Task 10 (TDD)
 */
import { describe, it, expect } from "vitest";
import { emitPaletteTs } from "../../src/extract/emit-ts";
import type { Palette } from "../../src/extract/parse-themes";

describe("emitPaletteTs", () => {
  it("emits a typed const object with header", () => {
    const out = emitPaletteTs({
      name: "DarkPalette",
      palette: { gold: "#D4A24C", textPrimary: "#FAFAFA" } as unknown as Palette,
    });
    expect(out).toContain("AUTOGENERATED");
    expect(out).toContain("export const DarkPalette = {");
    expect(out).toContain('gold: "#D4A24C",');
    expect(out).toContain('textPrimary: "#FAFAFA",');
    expect(out).toContain("} as const;");
    expect(out).toContain("export type DarkPalette = typeof DarkPalette;");
  });

  it("alphabetizes keys for stable output", () => {
    const out = emitPaletteTs({
      name: "DarkPalette",
      palette: {
        gold: "#A",
        background: "#B",
        textPrimary: "#C",
      } as unknown as Palette,
    });
    const idxBg = out.indexOf("background");
    const idxGold = out.indexOf("gold");
    const idxTp = out.indexOf("textPrimary");
    expect(idxBg).toBeLessThan(idxGold);
    expect(idxGold).toBeLessThan(idxTp);
  });

  it("is byte-stable across key-insertion-order permutations", () => {
    const a = emitPaletteTs({
      name: "P",
      palette: { a: "#1", b: "#2" } as unknown as Palette,
    });
    const b = emitPaletteTs({
      name: "P",
      palette: { b: "#2", a: "#1" } as unknown as Palette,
    });
    expect(a).toBe(b);
  });
});
