/**
 * emit-css.ts — emit CSS custom properties under :root (dark) or .theme-light.
 * Property names are kebab-cased and prefixed with `--color-`.
 */
import type { Palette } from "./parse-themes";

const camelToKebab = (s: string): string =>
  s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

export interface EmitCssArgs {
  mode: "dark" | "light";
  palette: Palette;
}

export function emitPaletteCss({ mode, palette }: EmitCssArgs): string {
  const selector = mode === "dark" ? ":root" : ".theme-light";
  const entries = Object.entries(palette).sort(([a], [b]) => a.localeCompare(b));
  const body = entries
    .map(([k, v]) => `  --color-${camelToKebab(k)}: ${v};`)
    .join("\n");
  return (
    `/* AUTOGENERATED — extracted from caps-armory-app/constants/themes.ts. Do not edit. */\n` +
    `${selector} {\n${body}\n}\n`
  );
}
