/**
 * emit-ts.ts — emit a typed `as const` palette module.
 */
import type { Palette } from "./parse-themes";

export interface EmitArgs {
  name: string;
  palette: Palette;
}

export function emitPaletteTs({ name, palette }: EmitArgs): string {
  const entries = Object.entries(palette).sort(([a], [b]) => a.localeCompare(b));
  const body = entries.map(([k, v]) => `  ${k}: "${v}",`).join("\n");
  return (
    `// AUTOGENERATED — extracted from caps-armory-app/constants/themes.ts. Do not edit.\n` +
    `export const ${name} = {\n${body}\n} as const;\n\n` +
    `export type ${name} = typeof ${name};\n`
  );
}
