/**
 * manifest.ts — Inter Variable shard manifest + CSS builder.
 *
 * Hand-curated against @fontsource-variable/inter@5.1.0 release CSS.
 * Update only when bumping @fontsource-variable/inter.
 */

export interface FontShard {
  file: string;
  unicodeRange: string;
}

export const INTER_SHARDS: FontShard[] = [
  {
    file: "inter-latin-wght-normal.woff2",
    unicodeRange:
      "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
  },
  {
    file: "inter-latin-ext-wght-normal.woff2",
    unicodeRange:
      "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
  },
  {
    file: "inter-cyrillic-wght-normal.woff2",
    unicodeRange:
      "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
  },
  {
    file: "inter-cyrillic-ext-wght-normal.woff2",
    unicodeRange:
      "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
  },
  {
    file: "inter-greek-wght-normal.woff2",
    unicodeRange: "U+0370-03FF",
  },
  {
    file: "inter-greek-ext-wght-normal.woff2",
    unicodeRange: "U+1F00-1FFF",
  },
  {
    file: "inter-vietnamese-wght-normal.woff2",
    unicodeRange:
      "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
  },
];

export function buildFontCss(shards: FontShard[]): string {
  const blocks = shards.map(
    (s) =>
      `@font-face {\n` +
      `  font-family: "Inter Variable";\n` +
      `  src: url("./${s.file}") format("woff2-variations");\n` +
      `  font-weight: 100 900;\n` +
      `  font-style: normal;\n` +
      `  font-display: swap;\n` +
      `  unicode-range: ${s.unicodeRange};\n` +
      `}\n`,
  );
  return (
    `/* AUTOGENERATED — extracted from @fontsource-variable/inter. Do not edit. */\n` +
    blocks.join("\n")
  );
}
