// AUTOGENERATED — extracted from caps-armory-app/constants/themes.ts. Do not edit.
export const DarkPalette = {
  background: "#0A0A0A",
  black: "#000000",
  border: "#2A2A2A",
  cancelled: "#7A7A7A",
  danger: "#D65B4F",
  darkGrey: "#333333",
  gold: "#C8A96E",
  goldLight: "#D4BC8A",
  info: "#6B8DA8",
  olive: "#7A8B5C",
  oliveLight: "#96A878",
  oliveMuted: "#5C6B42",
  success: "#7A8B5C",
  surface: "#141414",
  surfaceElevated: "#1E1E1E",
  textMuted: "#A8A29E",
  textPrimary: "#F0EDE6",
  textSecondary: "#ADA89C",
  warning: "#D4A44E",
  white: "#FFFFFF",
} as const;

export type DarkPalette = typeof DarkPalette;
