// AUTOGENERATED — extracted from caps-armory-app/constants/themes.ts. Do not edit.
export const LightPalette = {
  background: "#FFFFFF",
  black: "#000000",
  border: "#E0DDD6",
  cancelled: "#7A7A7A",
  danger: "#C44030",
  darkGrey: "#333333",
  gold: "#9E8451",
  goldLight: "#B8A070",
  info: "#4A7A9A",
  olive: "#5C7A3C",
  oliveLight: "#7A9A5C",
  oliveMuted: "#4A6630",
  success: "#5C7A3C",
  surface: "#F5F3EF",
  surfaceElevated: "#FFFFFF",
  textMuted: "#8A8580",
  textPrimary: "#1A1A1A",
  textSecondary: "#5A5650",
  warning: "#B8872E",
  white: "#FFFFFF",
} as const;

export type LightPalette = typeof LightPalette;
